name: web
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = https://nix.monade.li https://1lab.cachix.org
            extra-trusted-public-keys = nix.monade.li:2Zgy59ai/edDBizXByHMqiGgaHlE04G6Nzuhx1RPFgo= 1lab.cachix.org-1:eYjd9F9RfibulS4OSFBYeaTMxWojPYLyMqgJHDvG1fs=
      - uses: cachix/cachix-action@v15
        with:
          name: ncfavier
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: 1lab
      - name: Build
        run: |
          web=$(nix -L build --print-out-paths)
          cp -rL --no-preserve=mode,ownership,timestamps "$web" pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: pages
          retention-days: 1
  deploy:
    if: github.ref_name == 'main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
